#
# Makefile for misc devices that really don't fit anywhere else.
#
# include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
obj-y += lf810_tianan_hx8394d_wxga_ips_boe.o



